[package]
authors = ["Alejandro Gaviria <mr.gaviria@gmail.com>"]
name = "coyete"
version = "0.1.0"

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
serde = "1.0.11"
serde_derive = "1.0.11"
toml = "0.4.5"
